version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:7.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80